---------------------- DB CREATE ----------------------

REM **********************************************************************************
REM este creat tabelul REGIUNI pentru a retine informatii despre regiuni pentru tari *
REM tabelul TARI are o cheie externa catre acest tabel                               *
REM **********************************************************************************
PROMPT ****** creating REGIUNI table...

CREATE TABLE regiuni (
    id_regiune   VARCHAR2(2),
    nume_regiune VARCHAR2(40),
    
    CONSTRAINT pk_regiune PRIMARY KEY (id_regiune)
);


REM ******************************************************
REM este creat tabelul TARI pentru a retine informatii   *
REM despre tari ale membrilor si, implicit, echipe       *
REM tabelul MEMBRI are o cheie externa catre acest tabel *
REM ******************************************************
PROMPT ****** creating TARI table...

CREATE TABLE tari (
    id_tara    VARCHAR2(2),
    id_regiune VARCHAR2(2) NOT NULL,
    nume_tara  VARCHAR2(60),
    
    CONSTRAINT pk_tara PRIMARY KEY (id_tara),
    CONSTRAINT fk_tara_regiune FOREIGN KEY (id_regiune)
        REFERENCES regiuni(id_regiune) ON DELETE CASCADE
);


REM ***********************************************************************
REM este creat tabelul TIPURI_EVENIMENT pentru a retine informatii despre *
REM magnitudinea turneului organizat si natura acestuia                   *
REM tabelul TURNEE are o cheie externa catre acest tabel                  *
REM ***********************************************************************
PROMPT ****** creating TIPURI_EVENIMENT table...

CREATE TABLE tipuri_eveniment (
    id_tip_eveniment VARCHAR2(2),
    nume_tip         VARCHAR2(20),
    descriere        VARCHAR2(250),
    
    CONSTRAINT pk_tip_eveniment PRIMARY KEY (id_tip_eveniment)
);


REM *************************************************************
REM este creat tabelul ROLURI pentru a retine informatii despre *
REM rolurile asignate jucatorilor                               *
REM tabelul JUCATORI are o cheie externa catre acest tabel      *
REM *************************************************************
PROMPT ****** creating ROLURI table...

CREATE TABLE roluri (
    id_rol   VARCHAR2(3),
    nume_rol VARCHAR2(25),
    
    CONSTRAINT pk_rol PRIMARY KEY (id_rol)
);


REM *****************************************************************************
REM este creat tabelul HARTI pentru a retine informatii despre setul de harti   *
REM valabil in joc si care dintre acestea sunt jucate activ la nivel competitiv *
REM tabelul INSTANTE_MECI_HARTA are o cheie externa catre acest tabel           *
REM *****************************************************************************
PROMPT ****** creating HARTI table...

CREATE TABLE harti (
    id_harta NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    nume_harta VARCHAR2(30),
    pool_activ NUMBER(1) DEFAULT 0 NOT NULL,
    
    CONSTRAINT pk_harta PRIMARY KEY (id_harta),
    CONSTRAINT chk_pool_activ CHECK (pool_activ IN (0, 1))
);


REM ************************************************************
REM este creat tabelul ORGANIZATORI pentru a retine informatii *
REM despre corpurile logistice ce se ocupa de evenimente       *
REM tabelul TURNEE are o cheie externa catre acest tabel       * 
REM ************************************************************
PROMPT ****** creating ORGANIZATORI table...

CREATE TABLE organizatori (
    id_organizator NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 3000 CACHE 20 NOORDER),
    nume_organizator VARCHAR2(40),
    site_web         VARCHAR2(100),
    email_contact    VARCHAR2(50),
    
    CONSTRAINT pk_organizator PRIMARY KEY (id_organizator),
    CONSTRAINT chk_valid_website_org
        CHECK(REGEXP_LIKE(site_web, '^(https?://)?([a-zA-Z0-9.-]+)\.([a-zA-Z]{2,})(/.*)?$')),
    CONSTRAINT chk_valid_email
        CHECK(REGEXP_LIKE(email_contact, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);


REM ***************************************************************
REM este creat tabelul SPONSORI pentru a retine informatii despre *
REM corpurile care suporta financiar echipele profesioniste       *
REM tabelul SPONSORIZARI are o cheie externa catre acest tabel    *
REM ***************************************************************
PROMPT ****** creating SPONSORI table...

CREATE TABLE sponsori (
    id_sponsor NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 5000 CACHE 20 NOORDER),
    nume_sponsor       VARCHAR2(40),
    domeniu_activitate VARCHAR2(40),
    site_web           VARCHAR2(100),
    
    CONSTRAINT pk_sponsor PRIMARY KEY (id_sponsor),
    CONSTRAINT chk_valid_website_spn
        CHECK(REGEXP_LIKE(site_web, '^(https?://)?([a-zA-Z0-9.-]+)\.([a-zA-Z]{2,})(/.*)?$'))
);


REM **************************************************************
REM este creat tabelul ECHIPE pentru a retine informatii despre  *
REM organizatiile ce participa la turnee                         *
REM tabelele SPONSORIZARI, ISTORIC_CONTRACTE si PARTICIPARE_MECI *
REM au chei externe catre acest tabel                            *
REM ************************************************************** 
PROMPT ****** creating ECHIPE table...

CREATE TABLE echipe (
    id_echipa NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 100000 CACHE 20 NOORDER),
    nume_echipa     VARCHAR2(30),
    tag_echipa      VARCHAR2(5),
    ranking_mondial INTEGER,
    logo_url        VARCHAR2(100),
    
    CONSTRAINT pk_echipa PRIMARY KEY (id_echipa),
    CONSTRAINT chk_nume_echipa_valid CHECK (LENGTH(nume_echipa) > 2)
);


REM *************************************************************
REM este creat tabelul TURNEE pentru a retine informatii despre *
REM evenimentele tinute la care participa echipele              *
REM tabelul MECIURI are o cheie externe catre acest tabel       *
REM *************************************************************
PROMPT ****** creating TURNEE table...

CREATE TABLE turnee (
    id_turneu NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    id_organizator   NUMBER NOT NULL,
    id_tip_eveniment VARCHAR2(2) NOT NULL,
    nume_turneu      VARCHAR2(40),
    data_inceput     DATE NOT NULL,
    data_sfarsit     DATE,
    locatie_oras     VARCHAR2(40),
    premiu_total_usd NUMBER,
    
    CONSTRAINT pk_turneu PRIMARY KEY (id_turneu),
    CONSTRAINT fk_organizator FOREIGN KEY (id_organizator)
        REFERENCES organizatori(id_organizator) ON DELETE CASCADE,
    CONSTRAINT fk_tip_eveniment FOREIGN KEY (id_tip_eveniment)
        REFERENCES tipuri_eveniment(id_tip_eveniment) ON DELETE CASCADE,
    CONSTRAINT chk_perioada_valida_turneu CHECK (data_sfarsit >= data_inceput)
);


REM *************************************************************
REM este creat tabelul MEMBRI pentru a retine informatii despre * 
REM indivizii ce apartin scenei profesioniste a jocului         *
REM este superclasa pentru JUCATORI si ANTRENORI                *
REM tabelele ISTORIC_CONTRACTE, STATISTICI_INDIVIDUALE          *
REM au chei externe catre acest tabel                           *
REM *************************************************************
PROMPT ****** creating MEMBRI table...

CREATE TABLE membri (
    id_membru NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    id_tara      VARCHAR2(2),
    nume         VARCHAR2(30),
    prenume      VARCHAR2(30),
    nickname     VARCHAR2(25),
    data_nastere DATE,
    
    CONSTRAINT pk_membru PRIMARY KEY (id_membru),
    CONSTRAINT fk_tara FOREIGN KEY (id_tara)
        REFERENCES tari(id_tara) ON DELETE SET NULL
);


REM **********************************************************************
REM este creat tabelul JUCATORI pentru a retine detalii despre           *
REM membri ce participa in mod activ la evenimentele profesioniste       *
REM tabelul STATISTICI_INDIVIDUALE are o cheie externa catre acest tabel *
REM **********************************************************************
PROMPT ****** creating JUCATORI table...

CREATE TABLE jucatori (
    id_jucator NUMBER,
    id_rol        VARCHAR2(3) DEFAULT 'RFL' NOT NULL,
    rezolutie     VARCHAR2(20),
    sensitivitate NUMBER(4, 2),
    dpi_mouse     NUMBER,
    
    CONSTRAINT pk_jucator PRIMARY KEY (id_jucator),
    CONSTRAINT fk_membru_jucator FOREIGN KEY (id_jucator)
        REFERENCES membri(id_membru) ON DELETE CASCADE,
    CONSTRAINT fk_rol FOREIGN KEY (id_rol)
        REFERENCES roluri(id_rol) ON DELETE CASCADE
);


REM *************************************************************
REM este creat tabelul ANTRENORI pentru a retine detalii despre *
REM personalul din spatele jucatorilor profesionisti            *
REM *************************************************************
PROMPT ****** creating ANTRENORI table...

CREATE TABLE antrenori (
    id_antrenor     NUMBER,
    stil_antrenorat VARCHAR2(20) DEFAULT 'tactical',
    ani_experienta  INTEGER,
    
    CONSTRAINT pk_antrenor PRIMARY KEY (id_antrenor),
    CONSTRAINT fk_membru_antrenor FOREIGN KEY (id_antrenor)
        REFERENCES membri(id_membru) ON DELETE CASCADE
);


REM ************************************************************
REM este creat tabelul SPONSORIZARI pentru a retine informatii *
REM despre contractele dintre ECHIPE si SPONSORI in detaliu    *
REM ************************************************************
PROMPT ****** creating SPONSORIZARI table...

CREATE TABLE sponsorizari (
    id_sponsorizare NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    id_echipa     NUMBER NOT NULL,
    id_sponsor    NUMBER NOT NULL,
    data_inceput  DATE NOT NULL,
    data_sfarsit  DATE,
    suma_contract NUMBER,
    
    CONSTRAINT pk_sponsorizare PRIMARY KEY (id_sponsorizare),
    CONSTRAINT fk_echipa_sponsorizata FOREIGN KEY (id_echipa)
        REFERENCES echipe(id_echipa) ON DELETE CASCADE,
    CONSTRAINT fk_sponsor FOREIGN KEY (id_sponsor)
        REFERENCES sponsori(id_sponsor) ON DELETE CASCADE,
    CONSTRAINT chk_perioada_valida_sponsorizare CHECK (data_sfarsit >= data_inceput)
);


REM ******************************************************************
REM este creat tabelul ISTORIC_CONTRACTE pentru a retine informatii  *
REM cu privire la relatiile dintre MEMBRI si ECHIPE la care au jucat *
REM ******************************************************************
PROMPT ****** creating ISTORIC_CONTRACTE table...

CREATE TABLE istoric_contracte (
    id_contract NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 100 CACHE 20 NOORDER),
    id_membru     NUMBER NOT NULL,
    id_echipa     NUMBER NOT NULL,
    data_inceput  DATE NOT NULL,
    data_sfarsit  DATE,
    salariu_lunar NUMBER,
    
    CONSTRAINT pk_contract PRIMARY KEY (id_contract),
    CONSTRAINT fk_membru FOREIGN KEY (id_membru)
        REFERENCES membri(id_membru) ON DELETE CASCADE,
    CONSTRAINT fk_echipa_contract FOREIGN KEY (id_echipa)
        REFERENCES echipe(id_echipa) ON DELETE CASCADE,
    CONSTRAINT chk_perioada_valida_contract CHECK (data_sfarsit >= data_inceput)
);


REM ************************************************************************
REM este creat tabelul MECIURI pentru a retine informatii despre disputele *
REM organizate in cadrul evenimentelor dintre echipele participante        *
REM tabelele INSTANTE_MECI_HARTA si PARTICIPAR_MECIURI                     *
REM au chei externe catre acest tabel                                      *
REM ************************************************************************
PROMPT ****** creating MECIURI table...

CREATE TABLE meciuri (
    id_meci NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    id_turneu   NUMBER NOT NULL,
    data_ora    DATE,
    format_meci VARCHAR2(3),

    CONSTRAINT pk_meci PRIMARY KEY (id_meci),
    CONSTRAINT fk_turneu FOREIGN KEY (id_turneu)
        REFERENCES turnee(id_turneu) ON DELETE CASCADE,
    CONSTRAINT chk_format CHECK
        (REGEXP_LIKE(format_meci, '^BO[1,3,5]$', 'i'))
);


REM *************************************************************
REM este creat tabelul INSTANTE_MECI_HARTA pentru a fi retinute *
REM informatii despre HARTI jucate in cadrul unor MECIURI       *
REM tabelul RUNDE are o cheie externa catre acest tabel         *
REM *************************************************************
PROMPT ****** creating INSTANTE_MECI_HARTA table...

CREATE TABLE instante_meci_harta (
    id_instanta NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    id_meci       NUMBER NOT NULL,
    id_harta      NUMBER NOT NULL,
    durata_minute INTEGER,

    CONSTRAINT pk_instanta PRIMARY KEY (id_instanta),
    CONSTRAINT fk_meci_instanta FOREIGN KEY (id_meci)
        REFERENCES meciuri(id_meci) ON DELETE CASCADE,
    CONSTRAINT fk_harta FOREIGN KEY (id_harta)
        REFERENCES harti(id_harta) ON DELETE CASCADE
);


REM *****************************************************************************
REM este creat tabelul RUNDE pentru a retine informatii cu privire la contextul *
REM detaliat din cadrul unei instante a unui meci desfasurat pe o harta         *
REM tabelul STATISTICI_INDIVIDUALE are o cheie externa catre acest tabel        * 
REM *****************************************************************************
REM **** EXPLICATIE CODURI REZULTATE ****
REM TRCT - Time Ran Out   (Victorie CT) *
REM ELCT - Elimination CT (Victorie CT) *
REM ELT  - Elimination T  (Victorie T)  *
REM BDCT - Bomb Defused   (Victorie CT) *
REM BET  - Bomb Exploded  (Victorie T)  *
REM *************************************
PROMPT ****** creating RUNDE table...

CREATE TABLE runde (
    id_runda NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 100000 CACHE 20 NOORDER),
    id_instanta  NUMBER NOT NULL,
    numar_runda  INTEGER NOT NULL,
    cod_rezultat VARCHAR2(4) NOT NULL,

    CONSTRAINT pk_runda PRIMARY KEY (id_runda),
    CONSTRAINT fk_instanta FOREIGN KEY (id_instanta)
        REFERENCES instante_meci_harta(id_instanta) ON DELETE CASCADE,
    CONSTRAINT chk_valid_round CHECK (numar_runda > 0),
    CONSTRAINT chk_cod_rezultat CHECK (cod_rezultat IN ('TRCT', 'ELCT', 'ELT', 'BDCT', 'BET'))
);


REM *****************************************************************************
REM este creat tabelul STATISTICI_INDIVIDUALE pentru a retine informatii despre *
REM performanta individuala pentru JUCATORI participanti din cadrul unor RUNDE  *
REM *****************************************************************************
PROMPT ****** creating STATISTICI_INDIVIDUALE table...

CREATE TABLE statistici_individuale (
    id_runda      NUMBER NOT NULL,
    id_jucator    NUMBER NOT NULL,
    kills         INTEGER DEFAULT 0 NOT NULL,
    assists       INTEGER DEFAULT 0 NOT NULL,
    damage        INTEGER DEFAULT 0 NOT NULL,
    headshots     INTEGER DEFAULT 0 NOT NULL,
    flash_assists INTEGER DEFAULT 0 NOT NULL,
    died          INTEGER DEFAULT 0 NOT NULL,
    
    CONSTRAINT pk_statistica PRIMARY KEY (id_runda, id_jucator),
    CONSTRAINT fk_runda FOREIGN KEY (id_runda)
        REFERENCES runde(id_runda),
    CONSTRAINT fk_jucator FOREIGN KEY (id_jucator)
        REFERENCES jucatori(id_jucator),
    CONSTRAINT chk_kls CHECK (kills BETWEEN 0 AND 5),
    CONSTRAINT chk_ast CHECK (assists BETWEEN 0 AND 5),
    CONSTRAINT chk_dmg CHECK (damage BETWEEN 0 AND 500),
    CONSTRAINT chk_hss CHECK (headshots BETWEEN 0 AND 5),
    CONSTRAINT chk_fla CHECK (flash_assists BETWEEN 0 AND 5),
    CONSTRAINT chk_ded CHECK (died IN (0, 1))
);


REM ******************************************************
REM este creat tabelul LOG_AUDIT_ECHIPE pentru a retine  *
REM istoricul interventiilor LMD asupra tabelului ECHIPE *
REM ******************************************************
PROMPT ****** creating LOG_AUDIT_ECHIPE table...

CREATE TABLE log_audit_echipe (
    id_log       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    utilizator   VARCHAR2(50),
    data_actiune DATE,
    tip_operatie VARCHAR2(20),
    
    CONSTRAINT pk_log_echipe PRIMARY KEY (id_log)
);

REM *************************************************************************
REM este creat tabelul ISTORIC_MOD_SCHEMA pentru a tine evidenta            *
REM incercarilor eronate de a modifica tabelele esentiale ale bazei de date *
REM *************************************************************************
PROMPT ****** creating ISTORIC_MOD_SCHEMA table...

CREATE TABLE istoric_mod_schema (
    id_intrare NUMBER GENERATED BY DEFAULT ON NULL
        AS IDENTITY (START WITH 1 CACHE 20 NOORDER),
    user_oracle    VARCHAR2(30),
    data_eveniment DATE,
    tip_eveniment  VARCHAR2(30),
    nume_obiect    VARCHAR2(30),
    tip_obiect     VARCHAR2(30),
    CONSTRAINT pk_intrare PRIMARY KEY (id_intrare)
);
